services:
  db:
    image: postgres:15
    container_name: service-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-database}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8001:8000" 
    volumes:
      - ./Backend:/app
    environment: 
      DATABASE_URL: "postgresql+asyncpg://postgres:admin@service-postgres:5432/database"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./Frontend/bankapp
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/bankapp:/app
    depends_on:
      - backend

volumes:
  postgres_db_data: